### ISSUE TITLE
Flujo del programa

### ISSUE THREAD

**Issue by Lainix** [Lainix/card-validator#4]
El usuario deberá ingresar a la página constituida por un form el cual se muestra a continuación.

Se le pedirá al usuario ingrese manualmente los campos de Nombre, CVV, Numero constituido por 16 digitos de la tarjeta de crédito y por ultimo se le pedirá elija en el menu desplegable el año y el mes de expiración de su tarjeta (estos dos campos fueron creados de esta manera para reducir el nivel de errores que se puedan cometer durante el proceso de captura).

*Valida el número de tarjeta
Las validaciones correspondientes a este campo serán las siguientes:

 -El usuario solo podrá ingresar 16 digitos
 -El campo solo acepta números.

*Válida CVV
Validaciones del campo:

 -El usuario solo podrá ingresar 3 dígitos
 -El campo solo acepta números.

*Valida Fecha Expiración
Campo será dividido en dos secciones: Mes y Año.

-Año

 - El campo consiste en una lista de 20 años comenzando desde el año en curso (2018) hasta el 2038. Será en formato "aaaa"

-Mes

 - El campo consiste en una lista desplegable con los doce meses que integran un año en formato "mm". El usuario solo puede seleccionar uno solo de los números. Esta sección esta diseñada de esta manera para reducir el porcentaje de errores.

*Valida nombre
El usuario ingresa nombre y apellidos tal y como se encuentra plasmado en su identifiacion oficial o tarjeta de crédito. El campo solo permite qué el usuario:

 - Ingrese un máximo de 60 caracteres.
 - Los caracteres deben de estar constituidos solo por letras. 
 - Se permite el uso de espacios.

**Comment by DolceLemus** [comment]
Eli este ya se puede cerrar. Se va a modificar un poco el README
